### ISSUE TITLE
ゴミファイルを削除する

### ISSUE THREAD

**Issue by ikad** [Phaya-nmt/resrv-ticket#10]
以下2つのファイルはゴミなので削除する。

README.rdocああｑa
README.rdoc

**Comment by hiro1357** [comment]
README.rdocああｑaを削除
.rdocは後から気づいたので、後程・・・

**Comment by kukun99** [comment]
とりあえず提示されていたファイルを消してプルリクエストしたので、完了したらクローズしてください
