### ISSUE TITLE
デフォルトのタイムゾーンとかロケールとか

### ISSUE THREAD

**Issue by ikad** [Phaya-nmt/resrv-ticket#18]
config/application.rb を編集して、
1.タイムゾーンをTokyoにする。
2.デフォルトロケールを:jaにする。

ただし、2.のロケールを変更すると辞書が必要になるので注意。
バリデーションとかのエラーメッセージを日本語にするなら結局辞書は必要。
この際なので辞書も用意する？？

**Comment by kukun99** [comment]
#25 にて、
1.タイムゾーンをTokyoにしました。
2.デフォルトロケールを:jaにしました。
3．辞書ファイル（.yml）をconfig/locates以下に配置しました。

作業完了およびマージ完了したのでクローズします。
